---
- name: update debian
  hosts: all
  become: yes
  tasks:

    - name: update all packages to their latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes
        autoclean: yes
        autoremove: yes
