---
- name: add ansible user
  hosts: all
  become: yes
  tasks:

    - name: install sudo
      apt:
        name: sudo
        state: present

    - name: create ansible user
      user:
        name: ansible
        shell: /bin/bash
        groups: sudo
        append: yes
      when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == 'Ubuntu' 

    - name: create ansible user
      user:
        name: ansible
        shell: /bin/bash
        groups: wheel 
        append: yes
      when: ansible_facts['os_family'] == "CentOS" or ansible_facts['os_family'] == "RedHat"

    - name: copy public key
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub')}}"

    - name: allow passwordless sudo
      copy:
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/ansible
